package com.maddox.il2.objects.air;

import com.maddox.rts.Property;

public class VampireF3 extends Vampire {

    static {
        Class class1 = VampireF3.class;
        new NetAircraft.SPAWN(class1);
        Property.set(class1, "iconFar_shortClassName", "Vampire");
        Property.set(class1, "meshName", "3DO/Plane/VampireF3(Multi1)/hier.him");
        Property.set(class1, "PaintScheme", new PaintSchemeFMPar06());
        Property.set(class1, "originCountry", PaintScheme.countryBritain);
        Property.set(class1, "yearService", 1946F);
        Property.set(class1, "yearExpired", 1948.5F);
        Property.set(class1, "FlightModel", "FlightModels/VampireF3.fmd");
        Property.set(class1, "cockpitClass", new Class[] { CockpitVampire.class });
        Property.set(class1, "LOSElevation", 1.1058F);
        Aircraft.weaponTriggersRegister(class1, new int[] { 0, 0, 0, 0, 9, 9, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2 });
        Aircraft.weaponHooksRegister(class1, new String[] { "_MGUN01", "_MGUN02", "_MGUN03", "_MGUN04", "_ExternalDev01", "_ExternalDev02", "_ExternalBomb01", "_ExternalBomb02", "_ExternalRock01", "_ExternalRock02", "_ExternalRock03", "_ExternalRock04", "_ExternalRock05", "_ExternalRock06", "_ExternalRock07", "_ExternalRock08" });
//        try
//        {
//            ArrayList arraylist = new ArrayList();
//            Property.set(class1, "weaponsList", arraylist);
//            HashMapInt hashmapint = new HashMapInt();
//            Property.set(class1, "weaponsMap", hashmapint);
//            byte byte0 = 16;
//            Aircraft._WeaponSlot a_lweaponslot[] = new Aircraft._WeaponSlot[byte0];
//            String s = "default";
//            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
//            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[2] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[3] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[4] = null;
//            a_lweaponslot[5] = null;
//            a_lweaponslot[6] = null;
//            a_lweaponslot[7] = null;
//            a_lweaponslot[8] = null;
//            a_lweaponslot[9] = null;
//            a_lweaponslot[10] = null;
//            a_lweaponslot[11] = null;
//            a_lweaponslot[12] = null;
//            a_lweaponslot[13] = null;
//            a_lweaponslot[14] = null;
//            a_lweaponslot[15] = null;
//            arraylist.add(s);
//            hashmapint.put(Finger.Int(s), a_lweaponslot);
//            s = "2xdpts";
//            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
//            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[2] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[3] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[4] = new Aircraft._WeaponSlot(9, "FuelTankGun_Vamp", 1);
//            a_lweaponslot[5] = new Aircraft._WeaponSlot(9, "FuelTankGun_Vamp", 1);
//            a_lweaponslot[6] = null;
//            a_lweaponslot[7] = null;
//            a_lweaponslot[8] = null;
//            a_lweaponslot[9] = null;
//            a_lweaponslot[10] = null;
//            a_lweaponslot[11] = null;
//            a_lweaponslot[12] = null;
//            a_lweaponslot[13] = null;
//            a_lweaponslot[14] = null;
//            a_lweaponslot[15] = null;
//            arraylist.add(s);
//            hashmapint.put(Finger.Int(s), a_lweaponslot);
//            s = "2x500lbs";
//            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
//            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[2] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[3] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[4] = null;
//            a_lweaponslot[5] = null;
//            a_lweaponslot[6] = new Aircraft._WeaponSlot(3, "BombGun500lbsE", 1);
//            a_lweaponslot[7] = new Aircraft._WeaponSlot(3, "BombGun500lbsE", 1);
//            a_lweaponslot[8] = null;
//            a_lweaponslot[9] = null;
//            a_lweaponslot[10] = null;
//            a_lweaponslot[11] = null;
//            a_lweaponslot[12] = null;
//            a_lweaponslot[13] = null;
//            a_lweaponslot[14] = null;
//            a_lweaponslot[15] = null;
//            arraylist.add(s);
//            hashmapint.put(Finger.Int(s), a_lweaponslot);
//            s = "2x500lbs_8xrkts";
//            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
//            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[2] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[3] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[4] = null;
//            a_lweaponslot[5] = null;
//            a_lweaponslot[6] = new Aircraft._WeaponSlot(3, "BombGun500lbsE", 1);
//            a_lweaponslot[7] = new Aircraft._WeaponSlot(3, "BombGun500lbsE", 1);
//            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[9] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[10] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[11] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[12] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[13] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[14] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[15] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            arraylist.add(s);
//            hashmapint.put(Finger.Int(s), a_lweaponslot);
//            s = "2xdpt_8xrkts";
//            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
//            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[2] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[3] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[4] = new Aircraft._WeaponSlot(9, "FuelTankGun_Vamp", 1);
//            a_lweaponslot[5] = new Aircraft._WeaponSlot(9, "FuelTankGun_Vamp", 1);
//            a_lweaponslot[6] = null;
//            a_lweaponslot[7] = null;
//            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[9] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[10] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[11] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[12] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[13] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[14] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[15] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            arraylist.add(s);
//            hashmapint.put(Finger.Int(s), a_lweaponslot);
//            s = "8xrkts";
//            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
//            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[2] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[3] = new Aircraft._WeaponSlot(0, "MGunHispanoMkIki", 150);
//            a_lweaponslot[4] = null;
//            a_lweaponslot[5] = null;
//            a_lweaponslot[6] = null;
//            a_lweaponslot[7] = null;
//            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[9] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[10] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[11] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[12] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[13] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[14] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            a_lweaponslot[15] = new Aircraft._WeaponSlot(2, "RocketGunHVAR5BEAU", 1);
//            arraylist.add(s);
//            hashmapint.put(Finger.Int(s), a_lweaponslot);
//            s = "none";
//            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
//            a_lweaponslot[0] = null;
//            a_lweaponslot[1] = null;
//            a_lweaponslot[2] = null;
//            a_lweaponslot[3] = null;
//            a_lweaponslot[4] = null;
//            a_lweaponslot[5] = null;
//            a_lweaponslot[6] = null;
//            a_lweaponslot[7] = null;
//            a_lweaponslot[8] = null;
//            a_lweaponslot[9] = null;
//            a_lweaponslot[10] = null;
//            a_lweaponslot[11] = null;
//            a_lweaponslot[12] = null;
//            a_lweaponslot[13] = null;
//            a_lweaponslot[14] = null;
//            a_lweaponslot[15] = null;
//            arraylist.add(s);
//            hashmapint.put(Finger.Int(s), a_lweaponslot);
//        }
//        catch(Exception exception) { }
    }
}
