
package com.maddox.il2.objects.air;

import com.maddox.JGP.Vector3d;
import com.maddox.il2.ai.*;
import com.maddox.il2.ai.air.*;
import com.maddox.il2.engine.*;
import com.maddox.il2.fm.*;
import com.maddox.il2.game.*;
import com.maddox.il2.objects.sounds.SndAircraft;
import com.maddox.il2.objects.weapons.GuidedMissileUtils;
import com.maddox.rts.*;
import com.maddox.sas1946.il2.util.Reflection;
import com.maddox.util.HashMapInt;
import java.io.IOException;
import java.util.ArrayList;


public class A7A extends A7navy
    implements TypeGuidedMissileCarrier, TypeCountermeasure, TypeThreatDetector
{

    public A7A()
    {
        guidedMissileUtils = new GuidedMissileUtils(this);
        hasChaff = false;
        hasFlare = false;
        lastChaffDeployed = 0L;
        lastFlareDeployed = 0L;
        lastCommonThreatActive = 0L;
        intervalCommonThreat = 1000L;
        lastRadarLockThreatActive = 0L;
        intervalRadarLockThreat = 1000L;
        lastMissileLaunchThreatActive = 0L;
        intervalMissileLaunchThreat = 1000L;
    }

    public long getChaffDeployed()
    {
        if(hasChaff)
            return lastChaffDeployed;
        else
            return 0L;
    }

    public long getFlareDeployed()
    {
        if(hasFlare)
            return lastFlareDeployed;
        else
            return 0L;
    }

    public void setCommonThreatActive()
    {
        long l = Time.current();
        if(l - lastCommonThreatActive > intervalCommonThreat)
        {
            lastCommonThreatActive = l;
            doDealCommonThreat();
        }
    }

    public void setRadarLockThreatActive()
    {
        long l = Time.current();
        if(l - lastRadarLockThreatActive > intervalRadarLockThreat)
        {
            lastRadarLockThreatActive = l;
            doDealRadarLockThreat();
        }
    }

    public void setMissileLaunchThreatActive()
    {
        long l = Time.current();
        if(l - lastMissileLaunchThreatActive > intervalMissileLaunchThreat)
        {
            lastMissileLaunchThreatActive = l;
            doDealMissileLaunchThreat();
        }
    }

    private void doDealCommonThreat()
    {
    }

    private void doDealRadarLockThreat()
    {
    }

    private void doDealMissileLaunchThreat()
    {
    }

    public GuidedMissileUtils getGuidedMissileUtils()
    {
        return guidedMissileUtils;
    }

    public void onAircraftLoaded()
    {
        super.onAircraftLoaded();
        guidedMissileUtils.onAircraftLoaded();
    }

    public void update(float f)
    {
        guidedMissileUtils.update();
        super.update(f);
    }

    static Class _mthclass$(String s)
    {
        try
        {
            return Class.forName(s);
        }
        catch(ClassNotFoundException classnotfoundexception)
        {
            throw new NoClassDefFoundError(classnotfoundexception.getMessage());
        }
    }

    private GuidedMissileUtils guidedMissileUtils;
    private boolean hasChaff;
    private boolean hasFlare;
    private long lastChaffDeployed;
    private long lastFlareDeployed;
    private long lastCommonThreatActive;
    private long intervalCommonThreat;
    private long lastRadarLockThreatActive;
    private long intervalRadarLockThreat;
    private long lastMissileLaunchThreatActive;
    private long intervalMissileLaunchThreat;

    static 
    {
        Class class1 = com.maddox.il2.objects.air.A7A.class;
        new NetAircraft.SPAWN(class1);
        Property.set(class1, "iconFar_shortClassName", "A-7A");
        Property.set(class1, "meshName", "3DO/Plane/A7A/hier.him");
        Property.set(class1, "PaintScheme", new PaintSchemeFMPar06());
        Property.set(class1, "yearService", 1966.9F);
        Property.set(class1, "yearExpired", 1994.3F);
        Property.set(class1, "FlightModel", "FlightModels/A7A.fmd:A7_FM");
        Property.set(class1, "cockpitClass", new Class[] {
            com.maddox.il2.objects.air.CockpitA7A.class, com.maddox.il2.objects.air.CockpitA7B_Bombardier.class
        });
        Aircraft.weaponTriggersRegister(class1, new int[] {
            0, 0, 9, 9, 2, 2, 2, 2, 9, 9, 
            9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 
            9, 9, 9, 9, 2, 2, 2, 2, 2, 2, 
            2, 2, 2, 2, 2, 2, 9, 9, 3, 3, 
            3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
            3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
            3, 3
        });
        Aircraft.weaponHooksRegister(class1, new String[] {
            "_CANNON01", "_CANNON02", "_ExternalDev01", "_ExternalDev02", "_ExternalRock01", "_ExternalRock02", "_ExternalRock03", "_ExternalRock04", "_ExternalDev03", "_ExternalDev04", 
            "_ExternalDev05", "_ExternalDev06", "_ExternalDev07", "_ExternalDev08", "_ExternalDev09", "_ExternalDev10", "_ExternalDev11", "_ExternalDev12", "_ExternalDev13", "_ExternalDev14", 
            "_ExternalDev15", "_ExternalDev16", "_ExternalDev17", "_ExternalDev18", "_ExternalRock05", "_ExternalRock06", "_ExternalRock07", "_ExternalRock08", "_ExternalRock09", "_ExternalRock10", 
            "_ExternalRock11", "_ExternalRock12", "_ExternalRock13", "_ExternalRock14", "_ExternalRock15", "_ExternalRock16", "_ExternalDev19", "_ExternalDev20", "_ExternalBomb01", "_ExternalBomb02", 
            "_ExternalBomb03", "_ExternalBomb04", "_ExternalBomb05", "_ExternalBomb06", "_ExternalBomb07", "_ExternalBomb08", "_ExternalBomb09", "_ExternalBomb10", "_ExternalBomb11", "_ExternalBomb12", 
            "_ExternalBomb13", "_ExternalBomb14", "_ExternalBomb15", "_ExternalBomb16", "_ExternalBomb17", "_ExternalBomb18", "_ExternalBomb19", "_ExternalBomb20", "_ExternalBomb21", "_ExternalBomb22", 
            "_ExternalBomb23", "_ExternalBomb24"
        });
        try
        {
            ArrayList arraylist = new ArrayList();
            Property.set(class1, "weaponsList", arraylist);
            HashMapInt hashmapint = new HashMapInt();
            Property.set(class1, "weaponsMap", hashmapint);
            byte byte0 = 62;
            String s = "default";
            Aircraft._WeaponSlot a_lweaponslot[] = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xAGM12C";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = null;
            a_lweaponslot[3] = null;
            a_lweaponslot[4] = null;
            a_lweaponslot[5] = null;
            a_lweaponslot[6] = null;
            a_lweaponslot[7] = null;
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[24] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[28] = null;
            a_lweaponslot[29] = null;
            a_lweaponslot[30] = null;
            a_lweaponslot[31] = null;
            a_lweaponslot[32] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[34] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[35] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2xAGM12C+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = null;
            a_lweaponslot[3] = null;
            a_lweaponslot[4] = null;
            a_lweaponslot[5] = null;
            a_lweaponslot[6] = null;
            a_lweaponslot[7] = null;
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[34] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[35] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "18xMk82";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "12xMk82+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[44] = null;
            a_lweaponslot[45] = null;
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2xAGM12C+4xM117";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = null;
            a_lweaponslot[3] = null;
            a_lweaponslot[4] = null;
            a_lweaponslot[5] = null;
            a_lweaponslot[6] = null;
            a_lweaponslot[7] = null;
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[24] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2xAGM12C+4xBLU2";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = null;
            a_lweaponslot[3] = null;
            a_lweaponslot[4] = null;
            a_lweaponslot[5] = null;
            a_lweaponslot[6] = null;
            a_lweaponslot[7] = null;
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[24] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8xBLU2";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[48] = null;
            a_lweaponslot[49] = null;
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[54] = null;
            a_lweaponslot[55] = null;
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[60] = null;
            a_lweaponslot[61] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8xBLU2+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[48] = null;
            a_lweaponslot[49] = null;
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[54] = null;
            a_lweaponslot[55] = null;
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunBlu2Napalm", 1);
            a_lweaponslot[60] = null;
            a_lweaponslot[61] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "18xCBU24";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "12xCBU24+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[44] = null;
            a_lweaponslot[45] = null;
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8xMk81";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[48] = null;
            a_lweaponslot[49] = null;
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[54] = null;
            a_lweaponslot[55] = null;
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[60] = null;
            a_lweaponslot[61] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8xMk81+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[48] = null;
            a_lweaponslot[49] = null;
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[54] = null;
            a_lweaponslot[55] = null;
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[60] = null;
            a_lweaponslot[61] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "12xMk81+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[44] = null;
            a_lweaponslot[45] = null;
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGunMk81", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8xMk82";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[48] = null;
            a_lweaponslot[49] = null;
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[54] = null;
            a_lweaponslot[55] = null;
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[60] = null;
            a_lweaponslot[61] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8xMk82+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[48] = null;
            a_lweaponslot[49] = null;
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[54] = null;
            a_lweaponslot[55] = null;
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[60] = null;
            a_lweaponslot[61] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "12xMk82+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[44] = null;
            a_lweaponslot[45] = null;
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "18xMk82";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "18xMk82SnakeEye";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "12xMk82SnakeEye+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[44] = null;
            a_lweaponslot[45] = null;
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[58] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGunMk82SnakeEye", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "12xM117";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xM117+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[48] = null;
            a_lweaponslot[49] = null;
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[54] = null;
            a_lweaponslot[55] = null;
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[60] = null;
            a_lweaponslot[61] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xMk83+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[48] = null;
            a_lweaponslot[49] = null;
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[54] = null;
            a_lweaponslot[55] = null;
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[60] = null;
            a_lweaponslot[61] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xMk84+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[48] = null;
            a_lweaponslot[49] = null;
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[54] = null;
            a_lweaponslot[55] = null;
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[60] = null;
            a_lweaponslot[61] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "6xM117";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[48] = null;
            a_lweaponslot[49] = null;
            a_lweaponslot[50] = null;
            a_lweaponslot[51] = null;
            a_lweaponslot[54] = null;
            a_lweaponslot[55] = null;
            a_lweaponslot[56] = null;
            a_lweaponslot[57] = null;
            a_lweaponslot[60] = null;
            a_lweaponslot[61] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "6xMk83";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "6xMk84";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8xM117+dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(0, "MGunColtMk12ki", 250);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(6, "RocketGunAIM9D", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "BombGunNull", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonP51PLN2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(9, "FuelTankGun_TankAD4", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "none";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            for(int i = 0; i < byte0; i++)
                a_lweaponslot[i] = null;

            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
        }
        catch(Exception exception) { }
    }
}