// Origin of this file: UNKNOWN!

package com.maddox.il2.objects.air;

import java.util.ArrayList;

import com.maddox.rts.Finger;
import com.maddox.rts.Property;
import com.maddox.util.HashMapInt;

public class F_86F_25E extends F_86F {

    public void update(float f) {
        super.update(f);
        if (this.FM.getSpeed() > 5F) {
            this.moveSlats(f);
            this.bSlatsOff = false;
        } else {
            this.slatsOff();
        }
    }

    protected void moveSlats(float f) {
        this.resetYPRmodifier();
        Aircraft.xyz[0] = Aircraft.cvt(this.FM.getAOA(), 6.8F, 15F, 0.0F, -0.15F);
        Aircraft.xyz[1] = Aircraft.cvt(this.FM.getAOA(), 6.8F, 15F, 0.0F, 0.1F);
        Aircraft.xyz[2] = Aircraft.cvt(this.FM.getAOA(), 6.8F, 15F, 0.0F, -0.065F);
        this.hierMesh().chunkSetAngles("SlatL_D0", 0.0F, Aircraft.cvt(this.FM.getAOA(), 6.8F, 15F, 0.0F, 8.5F), 0.0F);
        this.hierMesh().chunkSetLocate("SlatL_D0", Aircraft.xyz, Aircraft.ypr);
        Aircraft.xyz[1] = Aircraft.cvt(this.FM.getAOA(), 6.8F, 15F, 0.0F, -0.1F);
        this.hierMesh().chunkSetAngles("SlatR_D0", 0.0F, Aircraft.cvt(this.FM.getAOA(), 6.8F, 15F, 0.0F, 8.5F), 0.0F);
        this.hierMesh().chunkSetLocate("SlatR_D0", Aircraft.xyz, Aircraft.ypr);
    }

    protected void slatsOff() {
        if (this.bSlatsOff) {
            return;
        } else {
            this.resetYPRmodifier();
            Aircraft.xyz[0] = -0.15F;
            Aircraft.xyz[1] = 0.1F;
            Aircraft.xyz[2] = -0.065F;
            this.hierMesh().chunkSetAngles("SlatL_D0", 0.0F, 8.5F, 0.0F);
            this.hierMesh().chunkSetLocate("SlatL_D0", Aircraft.xyz, Aircraft.ypr);
            Aircraft.xyz[1] = -0.1F;
            this.hierMesh().chunkSetAngles("SlatR_D0", 0.0F, 8.5F, 0.0F);
            this.hierMesh().chunkSetLocate("SlatR_D0", Aircraft.xyz, Aircraft.ypr);
            this.bSlatsOff = true;
            return;
        }
    }

    static {
        Class class1 = F_86F_25E.class;
        new NetAircraft.SPAWN(class1);
        Property.set(class1, "iconFar_shortClassName", "F-86");
        Property.set(class1, "meshName", "3DO/Plane/F-86E(Multi1)/hier.him");
        Property.set(class1, "PaintScheme", new PaintSchemeFMPar06());
        Property.set(class1, "meshName_us", "3DO/Plane/F-86E(USA)/hier.him");
        Property.set(class1, "PaintScheme_us", new PaintSchemeFMPar06());
        Property.set(class1, "meshName_gb", "3DO/Plane/F-86E(Multi1)/hier.him");
        Property.set(class1, "PaintScheme_gb", new PaintSchemeFMPar1956());
        Property.set(class1, "meshName_it", "3DO/Plane/F-86E(Multi1)/hier.him");
        Property.set(class1, "PaintScheme_it", new PaintSchemeFMPar1956());
        Property.set(class1, "yearService", 1949.9F);
        Property.set(class1, "yearExpired", 1960.3F);
        Property.set(class1, "FlightModel", "FlightModels/F-86F-25E.fmd:JETERA");
        Property.set(class1, "cockpitClass", new Class[] { CockpitF_86F.class });
        Property.set(class1, "LOSElevation", 0.725F);
        Aircraft.weaponTriggersRegister(class1, new int[] { 0, 0, 0, 0, 0, 0, 9, 9, 9, 9, 9, 3, 3, 9, 3, 3, 9, 2, 2, 9, 2, 2, 9, 9, 9, 9, 9, 3, 3, 9, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3 });
        Aircraft.weaponHooksRegister(class1, new String[] { "_MGUN01", "_MGUN02", "_MGUN03", "_MGUN04", "_MGUN05", "_MGUN06", "_ExternalDev01", "_ExternalDev02", "_ExternalDev03", "_ExternalDev04", "_ExternalDev05", "_ExternalBomb01", "_ExternalBomb01", "_ExternalDev06", "_ExternalBomb02", "_ExternalBomb02", "_ExternalDev07", "_ExternalRock01", "_ExternalRock01", "_ExternalDev08", "_ExternalRock02", "_ExternalRock02", "_ExternalDev09", "_ExternalDev10", "_ExternalDev11", "_ExternalDev12", "_ExternalDev13", "_ExternalBomb03", "_ExternalBomb03", "_ExternalDev14", "_ExternalBomb04", "_ExternalBomb04", "_ExternalRock03", "_ExternalRock04", "_ExternalRock05", "_ExternalRock06", "_ExternalRock07", "_ExternalRock08", "_ExternalRock09", "_ExternalRock10", "_ExternalRock11", "_ExternalRock12", "_ExternalRock13", "_ExternalRock14", "_ExternalRock15", "_ExternalRock16", "_ExternalRock17", "_ExternalRock18", "_ExternalBomb07", "_ExternalBomb08" });
        try {
            ArrayList arraylist = new ArrayList();
            Property.set(class1, "weaponsList", arraylist);
            HashMapInt hashmapint = new HashMapInt();
            Property.set(class1, "weaponsMap", hashmapint);
            byte byte0 = 50;
            String s = "default";
            Aircraft._WeaponSlot a_lweaponslot[] = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x120dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x500lbs";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(9, "PylonF86_Bombs", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonF86_Bombs", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x750lbs";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(9, "PylonF86_Bombs", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(3, "BombGun750lbs", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonF86_Bombs", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(3, "BombGun750lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x750lbsM117";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(9, "PylonF86_Bombs", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonF86_Bombs", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x1000lbs";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(9, "PylonF86_Bombs", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(3, "BombGun1000lbs", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonF86_Bombs", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(3, "BombGun1000lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x1000lbsM114";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(9, "PylonF86_Bombs", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(3, "BombGun1000lbs_M114", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "PylonF86_Bombs", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(3, "BombGun1000lbs_M114", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x120dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            a_lweaponslot[22] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[23] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[24] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x120dt+2x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            a_lweaponslot[22] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[23] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[24] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            a_lweaponslot[22] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[23] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[24] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x75nap";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun75Napalm", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun75Napalm", 1);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x75nap+2x120dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun75Napalm", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun75Napalm", 1);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x75nap+2x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun75Napalm", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun75Napalm", 1);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x500";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x500+2x120dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x500+2x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(3, "BombGunNull", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x500+2x750";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun750lbs", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun750lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x500+2xM117";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x500";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun500lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x750";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun750lbs", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun750lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x750+2x120dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun750lbs", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun750lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x750+2x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun750lbs", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun750lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2xM117";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2xM117+2x120dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2xM117+2x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x1000";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun1000lbs", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun1000lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x1000+2x120dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun1000lbs", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun1000lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x1000+2x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun1000lbs", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun1000lbs", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2xM114";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun1000lbs_M114", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun1000lbs_M114", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2xM114+2x120dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun1000lbs_M114", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun1000lbs_M114", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2xM114+2x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "BombGun1000lbs_M114", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "BombGun1000lbs_M114", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "16xHVAR";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[34] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[35] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8xHVAR+2x120dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_120galR", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8xHVAR+2x207dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(1, "MGunBrowningM3", 270);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(1, "MGunBrowningM3b", 270);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(1, "MGunBrowningM3c", 270);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(9, "PylonF86_Outboard", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galL", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(9, "FuelTankGun_Tank207galR", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(2, "RocketGunHVARF84", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "none";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = null;
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
        } catch (Exception exception) {
        }
    }
}
