package com.maddox.il2.objects.air;

import java.util.ArrayList;

import com.maddox.rts.Finger;
import com.maddox.rts.Property;
import com.maddox.util.HashMapInt;

public class F_105D extends F_105 {

    public F_105D() {}

    static {
        Class class1 = F_105D.class;
        new NetAircraft.SPAWN(class1);
        Property.set(class1, "iconFar_shortClassName", "F-105D");
        Property.set(class1, "meshName", "3DO/Plane/F-105D/hier.him");
        Property.set(class1, "PaintScheme", new PaintSchemeFMPar06());
        Property.set(class1, "yearService", 1959F);
        Property.set(class1, "yearExpired", 1980F);
        Property.set(class1, "FlightModel", "FlightModels/F-105D.fmd:F105");
        Property.set(class1, "cockpitClass", new Class[] { CockpitF_105.class });
        Property.set(class1, "LOSElevation", 0.725F);
        Aircraft.weaponTriggersRegister(class1, new int[] { 0, 9, 9, 2, 2, 2, 2, 2, 2, 2, 2, 9, 9, 9, 9, 3, 3, 3, 3, 9, 9, 3, 3, 3, 3, 9, 9, 9, 9, 9, 9, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 9, 9, 9, 9, 9, 3, 3, 3, 3, 3, 3, 3, 9, 9, 2, 2, 2, 2, 2, 2,
            2, 2 });
        Aircraft.weaponHooksRegister(class1, new String[] { "_MGUN01", "_ExternalDev01", "_ExternalDev02", "_ExternalRock01", "_ExternalRock01", "_ExternalRock02", "_ExternalRock02", "_ExternalRock03", "_ExternalRock03", "_ExternalRock04",
            "_ExternalRock04", "_ExternalDev03", "_ExternalDev04", "_ExternalDev05", "_ExternalDev06", "_ExternalBomb01", "_ExternalBomb02", "_ExternalBomb03", "_ExternalBomb04", "_ExternalDev07", "_ExternalDev08", "_ExternalBomb05", "_ExternalBomb06",
            "_ExternalBomb07", "_ExternalBomb08", "_ExternalDev09", "_ExternalDev10", "_ExternalDev11", "_ExternalDev12", "_ExternalDev13", "_ExternalDev14", "_Rocket05", "_Rocket06", "_Rocket07", "_Rocket08", "_Rocket09", "_Rocket10", "_ExternalBomb09",
            "_ExternalBomb10", "_ExternalBomb11", "_ExternalBomb12", "_ExternalBomb13", "_ExternalBomb14", "_ExternalBomb15", "_ExternalBomb16", "_ExternalDev15", "_ExternalDev16", "_Dev17", "_Dev18", "_ExternalDev19", "_ExternalBomb17",
            "_ExternalBomb18", "_ExternalBomb19", "_ExternalBomb20", "_ExternalBomb21", "_ExternalBomb22", "_ExternalBomb23", "_ExternalDev20", "_Dev21", "_ExternalRocket11", "_ExternalRocket11", "_ExternalRocket12", "_ExternalRocket12",
            "_ExternalRocket13", "_ExternalRocket13", "_ExternalRocket14", "_ExternalRocket14" });
        String s = "";
        try {
            ArrayList arraylist = new ArrayList();
            Property.set(class1, "weaponsList", arraylist);
            HashMapInt hashmapint = new HashMapInt();
            Property.set(class1, "weaponsMap", hashmapint);
            byte byte0 = 67;
            s = "default";
            Aircraft._WeaponSlot a_lweaponslot[] = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xAIM9B";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_SidewinderL", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_SidewinderR", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x 450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xAIM9B + 2x 450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_SidewinderL", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_SidewinderR", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x500lbs Mk82";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x750lbs  M117";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x1000lbs Mk83";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x2000lbs Mk84 + 2x1000lbs Mk83";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(3, "BombGunMk84", 
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x2000lbs Mk84 + 5x1000lbs Mk83";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "3x2000lbs Mk84 + 2x1000lbs Mk83";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x2000lbs Mk84 + 2x1000lbs Mk83 + 1x600Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "FuelTankGun_335gal", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x1000lbs Mk83 + 2x 450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "1x2000lbs Mk84 + 2x1000lbs Mk83 + 2x 450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "BombGunMk84", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x750lbs M117 + 2x 450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "6x750lbs  M117";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[20] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[21] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[22] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[23] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[24] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "6x1000lbs Mk83";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[20] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[21] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[22] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[23] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            a_lweaponslot[24] = new Aircraft._WeaponSlot(3, "BombGunMk83", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "6xCBU24 Cluster";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[20] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[21] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[22] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[23] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[24] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "10x500lbs  Mk82";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "10x750lbs  M117";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "10x CBU24 Cluster";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "10x500lbs  Mk82 + 1x600Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "FuelTankGun_335gal", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "10x750lbs  M117 + 1x600Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "FuelTankGun_335gal", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "10x CBU24 Cluster + 1x600Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "FuelTankGun_335gal", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8x500lbs  Mk82 + 2x450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8x750lbs  M117 + 2x450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8x CBU24 Cluster + 2x450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "16x500lbs  Mk82";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "16x750lbs  M117";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "16x CBU24 Cluster";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xLAU3 + 2x CBU24 Cluster";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[20] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[34] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xLAU3 + 8x CBU24 Cluster";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[20] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[34] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xLAU3 + 2xLAU32";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[20] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(3, "Pylon_LAU3", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "Pylon_LAU3", 1);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[34] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[35] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "6x CBU24 Cluster + 4xLAU3 + 2xLAU32";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[20] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[27] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(3, "Pylon_LAU3", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "Pylon_LAU3", 1);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[34] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[35] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8x CBU24 Cluster + 2xLAU3";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[35] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "8x CBU24 Cluster + 2xLAU3 + 1x600Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[35] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "FuelTankGun_335gal", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "14x CBU24 Cluster + 2xLAU3";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "Pylon_LAU61", 1);
            a_lweaponslot[35] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(2, "RocketGunHYDRA", 19);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[45] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[46] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[47] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[48] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "6x500lbs  Mk82 + 2xAim-9B + Flares + 2x450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_SidewinderL", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "Pylon_LAU3", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(7, "RocketGunFlareNEW", 30);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunMk82", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "6x750lbs  M117 2xAim-9B + Flares + 2x450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_SidewinderL", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "Pylon_LAU3", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(7, "RocketGunFlareNEW", 30);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGun750lbsM117", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "6x CBU24 Cluster 2xAim-9B + Flares + 2x450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_SidewinderL", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "Pylon_LAU3", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(7, "RocketGunFlareNEW", 30);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[51] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[52] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[53] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[54] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[55] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[56] = new Aircraft._WeaponSlot(3, "BombGunCBU24", 1);
            a_lweaponslot[57] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            a_lweaponslot[58] = new Aircraft._WeaponSlot(9, "PylonF4TER", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "1xMk12 Nuclear Bomb + 2xAim-9B + Flares + 2x450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_SidewinderL", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[3] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[4] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "RocketGunAIM9B", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(3, "Pylon_LAU3", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(7, "RocketGunFlareNEW", 30);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "BombGunMk12", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "2x AGM12C + 2x450Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(9, "FuelTankGun_335gal", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[62] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            s = "4x AGM12C + 1x600Gal Dt";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(0, "MGunM61A1", 1040);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard", 1);
            a_lweaponslot[49] = new Aircraft._WeaponSlot(9, "PylonF100_Outboard2", 1);
            a_lweaponslot[50] = new Aircraft._WeaponSlot(3, "FuelTankGun_335gal", 1);
            a_lweaponslot[59] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[60] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[61] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[62] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[63] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[64] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            a_lweaponslot[65] = new Aircraft._WeaponSlot(2, "RocketGunAGM12C", 1);
            a_lweaponslot[66] = new Aircraft._WeaponSlot(2, "RocketGunNull", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "none";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            for (int i = 0; i < byte0; i++)
                a_lweaponslot[i] = null;

            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
        } catch (Exception exception) {
            System.out.println("Error on F-105D Loadout: " + s);
            exception.printStackTrace();
        }
    }
}