package com.maddox.il2.objects.air;

import java.util.ArrayList;

import com.maddox.rts.Finger;
import com.maddox.rts.Property;
import com.maddox.util.HashMapInt;

public class Huey_Doorless_Gunship extends HueyX implements TypeScout, TypeTransport {
    static {
        final Class class1 = Huey_Doorless_Gunship.class;
        new NetAircraft.SPAWN(class1);
        Property.set(class1, "iconFar_shortClassName", "Huey");
        Property.set(class1, "meshName", "3DO/Plane/Huey_Doorless_Gunship/hier.him");
        Property.set(class1, "PaintScheme", new PaintSchemeFMPar05());
        Property.set(class1, "yearService", 1956F);
        Property.set(class1, "yearExpired", 1986.5F);
        Property.set(class1, "FlightModel", "FlightModels/Huey.fmd:Huey_FM");
        Property.set(class1, "cockpitClass", new Class[] { CockpitHuey1B.class });
        Aircraft.weaponTriggersRegister(class1, new int[] { 10, 11, 9, 9, 9, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 9, 9, 9, 9, 9, 9, 0, 0, 0, 0, 9, 9, 1, 1, 2, 2, 2, 2, 9, 9, 1, 1 });
        Aircraft.weaponHooksRegister(class1, new String[] { "_MGUN01", "_MGUN02", "_ExternalDev01", "_ExternalDev02", "_ExternalDev03", "_ExternalRock01", "_ExternalRock02", "_ExternalRock03", "_ExternalRock04", "_ExternalRock05", "_ExternalRock06", "_ExternalRock07", "_ExternalRock08", "_ExternalRock09", "_ExternalRock10", "_ExternalRock11", "_ExternalRock12", "_ExternalRock13", "_ExternalRock14", "_ExternalRock15", "_ExternalRock16", "_ExternalRock17", "_ExternalRock18", "_ExternalDev04", "_ExternalDev05", "_ExternalDev06", "_ExternalDev07", "_ExternalDev08", "_ExternalDev09", "_MGUN03", "_MGUN04", "_MGUN05", "_MGUN06", "_ExternalDev10", "_ExternalDev11", "_MGUN07", "_MGUN08", "_ExternalRock19", "_ExternalRock20", "_ExternalRock21", "_ExternalRock22", "_ExternalDev12", "_ExternalDev13", "_MGUN09", "_MGUN10" });
        try {
            final ArrayList arraylist = new ArrayList();
            Property.set(class1, "weaponsList", arraylist);
            final HashMapInt hashmapint = new HashMapInt();
            Property.set(class1, "weaponsMap", hashmapint);
            final byte byte0 = 45;
            Aircraft._WeaponSlot a_lweaponslot[] = new Aircraft._WeaponSlot[byte0];
            String s = "default";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(10, "MGunM60", 500);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(11, "MGunM60", 500);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x30Cal_2xDoorGunners";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(10, "MGunM60", 500);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(11, "MGunM60", 500);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "GunPod", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(9, "MGGuns", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xGun_2xM158_2xDoorGunners";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(10, "MGunM60", 500);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(11, "MGunM60", 500);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "GunPod", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(9, "MGGuns", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(9, "PylonM158", 1);
            a_lweaponslot[34] = new Aircraft._WeaponSlot(9, "PylonM158", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x30Cal_2xLAU3_2xDoorGunners";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(10, "MGunM60", 500);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(11, "MGunM60", 500);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "GunPod", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[18] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(9, "MGGuns", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(9, "Pylon_LAU3", 1);
            a_lweaponslot[34] = new Aircraft._WeaponSlot(9, "Pylon_LAU3", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4xGun_1xM158_1xSUU11_2xDoorGunners";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(10, "MGunM60", 500);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(11, "MGunM60", 500);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "GunPod", 1);
            a_lweaponslot[5] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[6] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[7] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[8] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[9] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[10] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[11] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[12] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[13] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[14] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[15] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[16] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[17] = new Aircraft._WeaponSlot(2, "RocketGunFFARMk4_2", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonSUU11_Huey", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(9, "MGGuns", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(9, "PylonM158", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(1, "MGunMiniGun", 1500);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x30Cal_2xSUU11_2xDoorGunners";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(10, "MGunM60", 500);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(11, "MGunM60", 500);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "GunPod", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(9, "PylonSUU11_Huey", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonSUU11_Huey", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(9, "MGGuns", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[35] = new Aircraft._WeaponSlot(1, "MGunMiniGun", 1500);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(1, "MGunMiniGun", 1500);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x30Cal_8xZuni_2xDoorGunners";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(10, "MGunM60", 500);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(11, "MGunM60", 500);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "GunPod", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            a_lweaponslot[20] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            a_lweaponslot[21] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            a_lweaponslot[22] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(9, "MGGuns", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(9, "Pylon_Zuni", 1);
            a_lweaponslot[34] = new Aircraft._WeaponSlot(9, "Pylon_Zuni", 1);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            a_lweaponslot[40] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x30Cal_1xSUU11_4xZuni_2xDoorGunners";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(10, "MGunM60", 500);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(11, "MGunM60", 500);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "GunPod", 1);
            a_lweaponslot[19] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            a_lweaponslot[20] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[21] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            a_lweaponslot[22] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonSUU11_Huey", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(9, "MGGuns", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[33] = new Aircraft._WeaponSlot(9, "Pylon_Zuni", 1);
            a_lweaponslot[36] = new Aircraft._WeaponSlot(1, "MGunMiniGun", 1500);
            a_lweaponslot[37] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            a_lweaponslot[38] = new Aircraft._WeaponSlot(2, "BombGunNull", 1);
            a_lweaponslot[39] = new Aircraft._WeaponSlot(2, "RocketGun5inchZuni", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "4x30Cal_2x20mm_2xDoorGunners";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(10, "MGunM60", 500);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(11, "MGunM60", 500);
            a_lweaponslot[2] = new Aircraft._WeaponSlot(9, "GunPod", 1);
            a_lweaponslot[25] = new Aircraft._WeaponSlot(9, "PylonXM13POD", 1);
            a_lweaponslot[26] = new Aircraft._WeaponSlot(9, "PylonXM13POD", 1);
            a_lweaponslot[28] = new Aircraft._WeaponSlot(9, "MGGuns", 1);
            a_lweaponslot[29] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[30] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[31] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[32] = new Aircraft._WeaponSlot(0, "MGunBrowning303t", 300);
            a_lweaponslot[43] = new Aircraft._WeaponSlot(1, "MGunHispanoMkIki", 200);
            a_lweaponslot[44] = new Aircraft._WeaponSlot(1, "MGunHispanoMkIki", 200);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "Wounded";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            a_lweaponslot[0] = new Aircraft._WeaponSlot(10, "MGunM60", 500);
            a_lweaponslot[1] = new Aircraft._WeaponSlot(11, "MGunM60", 500);
            a_lweaponslot[41] = new Aircraft._WeaponSlot(9, "stretcherR", 1);
            a_lweaponslot[42] = new Aircraft._WeaponSlot(9, "stretcherL", 1);
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
            s = "none";
            a_lweaponslot = new Aircraft._WeaponSlot[byte0];
            arraylist.add(s);
            hashmapint.put(Finger.Int(s), a_lweaponslot);
        } catch (final Exception exception) {
        }
    }
}
