package com.maddox.il2.objects;

import com.maddox.il2.ai.ScoreCounter;
import com.maddox.il2.ai.ground.TgtInfantry;
import com.maddox.il2.objects.air.Aircraft;
import com.maddox.il2.objects.air.BF_109G6GRAF;
import com.maddox.il2.objects.air.BF_109G6HARTMANN;
import com.maddox.il2.objects.air.DXXI_SARJA3_SARVANTO;
import com.maddox.il2.objects.air.I_16TYPE24SAFONOV;
import com.maddox.il2.objects.air.ME_262A1ANOWOTNY;
import com.maddox.il2.objects.air.MIG_3POKRYSHKIN;
import com.maddox.il2.objects.air.P_39NPOKRYSHKIN;
import com.maddox.il2.objects.air.P_39Q15RECHKALOV;
import com.maddox.il2.objects.air.Scheme1;
import com.maddox.il2.objects.air.Scheme2;
import com.maddox.il2.objects.air.Scheme3;
import com.maddox.il2.objects.air.Scheme4;
import com.maddox.il2.objects.air.Scheme5;
import com.maddox.il2.objects.air.Scheme6;
import com.maddox.il2.objects.air.Scheme7;
import com.maddox.il2.objects.air.YAK_9TALBERT;
import com.maddox.il2.objects.bridges.LongBridge;
import com.maddox.il2.objects.ships.BigshipGeneric;
import com.maddox.il2.objects.ships.Ship;
import com.maddox.il2.objects.ships.ShipGeneric;
import com.maddox.il2.objects.trains.Wagon;
import com.maddox.il2.objects.vehicles.artillery.AAA;
import com.maddox.il2.objects.vehicles.artillery.Artillery;
import com.maddox.il2.objects.vehicles.artillery.ArtilleryGeneric;
import com.maddox.il2.objects.vehicles.artillery.SArtillery;
import com.maddox.il2.objects.vehicles.artillery.STank;
import com.maddox.il2.objects.vehicles.artillery.SWagon;
import com.maddox.il2.objects.vehicles.cars.CarGeneric;
import com.maddox.il2.objects.vehicles.planes.PlaneGeneric;
import com.maddox.il2.objects.vehicles.radios.BeaconGeneric;
import com.maddox.il2.objects.vehicles.stationary.Stationary;
import com.maddox.il2.objects.vehicles.stationary.StationaryGeneric;
import com.maddox.il2.objects.vehicles.tanks.Tank;
import com.maddox.il2.objects.vehicles.tanks.TankGeneric;

public class ScoreRegister
{
    public static void load()
    {
    }

    static 
    {
        ScoreCounter.register(Scheme1.class, 0, 100D, 300D);
        ScoreCounter.register(Scheme2.class, 0, 200D, 400D);
        ScoreCounter.register(Scheme3.class, 0, 200D, 400D);
        ScoreCounter.register(Scheme4.class, 0, 400D, 400D);
        ScoreCounter.register(Scheme5.class, 0, 200D, 400D);
        ScoreCounter.register(Scheme6.class, 0, 300D, 400D);
        ScoreCounter.register(Scheme7.class, 0, 600D, 400D);
        ScoreCounter.register(BF_109G6HARTMANN.class, 0, 150D, 500D);
        ScoreCounter.register(BF_109G6GRAF.class, 0, 150D, 500D);
        ScoreCounter.register(I_16TYPE24SAFONOV.class, 0, 150D, 500D);
        ScoreCounter.register(ME_262A1ANOWOTNY.class, 0, 150D, 500D);
        ScoreCounter.register(MIG_3POKRYSHKIN.class, 0, 150D, 500D);
        ScoreCounter.register(P_39NPOKRYSHKIN.class, 0, 150D, 500D);
        ScoreCounter.register(P_39Q15RECHKALOV.class, 0, 150D, 500D);
        ScoreCounter.register(YAK_9TALBERT.class, 0, 150D, 500D);
        ScoreCounter.register(DXXI_SARJA3_SARVANTO.class, 0, 150D, 500D);
        ScoreCounter.register(Aircraft.class, 0, 100D, 400D);
        ScoreCounter.register(PlaneGeneric.class, 8, 20D, 400D);
        ScoreCounter.register(TankGeneric.class, 1, 40D, 400D);
        ScoreCounter.register(Tank.Wirbelwind.class, 1, 130D, 400D);
        ScoreCounter.register(Tank.T34.class, 1, 50D, 400D);
        ScoreCounter.register(Tank.T34_85.class, 1, 50D, 400D);
        ScoreCounter.register(Tank.KV1.class, 1, 55D, 400D);
        ScoreCounter.register(Tank.IS2.class, 1, 55D, 400D);
        ScoreCounter.register(Tank.PzVA.class, 1, 50D, 400D);
        ScoreCounter.register(Tank.PzVIE.class, 1, 55D, 400D);
        ScoreCounter.register(Tank.PzVIB.class, 1, 55D, 500D);
        ScoreCounter.register(STank.class, 1, 40D, 400D);
        ScoreCounter.register(TgtInfantry.class, 2, 10D, 100D);
        ScoreCounter.register(Artillery.Wirbelwind.class, 1, 70D, 400D);
        ScoreCounter.register(Artillery.T34.class, 1, 50D, 400D);
        ScoreCounter.register(Artillery.T34_85.class, 1, 50D, 400D);
        ScoreCounter.register(Artillery.KV1.class, 1, 55D, 400D);
        ScoreCounter.register(Artillery.IS2.class, 1, 55D, 400D);
        ScoreCounter.register(Artillery.PzVA.class, 1, 50D, 400D);
        ScoreCounter.register(Artillery.PzVIE.class, 1, 55D, 400D);
        ScoreCounter.register(Artillery.PzVIB.class, 1, 55D, 500D);
        ScoreCounter.register(Stationary.Wirbelwind.class, 1, 30D, 400D);
        ScoreCounter.register(Stationary.T34.class, 1, 30D, 400D);
        ScoreCounter.register(Stationary.T34_85.class, 1, 30D, 400D);
        ScoreCounter.register(Stationary.KV1.class, 1, 40D, 400D);
        ScoreCounter.register(Stationary.IS2.class, 1, 40D, 400D);
        ScoreCounter.register(Stationary.PzVA.class, 1, 30D, 400D);
        ScoreCounter.register(Stationary.PzVIE.class, 1, 40D, 400D);
        ScoreCounter.register(Stationary.PzVIB.class, 1, 40D, 500D);
        ScoreCounter.register(AAA.class, 4, 60D, 150D);
        ScoreCounter.register(SArtillery.class, 3, 30D, 100D);
        ScoreCounter.register(ArtilleryGeneric.class, 3, 30D, 100D);
        ScoreCounter.register(CarGeneric.class, 2, 25D, 100D);
        ScoreCounter.register(StationaryGeneric.class, 2, 25D, 100D);
        ScoreCounter.register(SWagon.class, 6, 30D, 100D);
        ScoreCounter.register(Wagon.class, 6, 30D, 100D);
        ScoreCounter.register(ShipGeneric.class, 7, 100D, 400D);
        ScoreCounter.register(BigshipGeneric.class, 7, 100D, 400D);
        ScoreCounter.register(Ship.Destroyer_USSR_Type7.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.Destroyer_USSR_Type7_44.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.Murgesku.class, 7, 250D, 600D);
        ScoreCounter.register(Ship.MBoat.class, 7, 250D, 600D);
        ScoreCounter.register(Ship.Tral.class, 7, 200D, 500D);
        ScoreCounter.register(Ship.Aurora.class, 7, 500D, 1000D);
        ScoreCounter.register(Ship.Marat.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.Kirov.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.Tramp.class, 7, 200D, 400D);
        ScoreCounter.register(Ship.Niobe.class, 7, 600D, 1200D);
        ScoreCounter.register(Ship.NiobeWithBeacon.class, 7, 600D, 1200D);
        ScoreCounter.register(Ship.Tanker.class, 7, 200D, 400D);
        ScoreCounter.register(Ship.Illmarinen.class, 7, 500D, 1000D);
        ScoreCounter.register(Ship.Vainamoinen.class, 7, 500D, 1000D);
        ScoreCounter.register(Ship.USSLexingtonCV2.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.USSSaratogaCV3.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.USSCVGeneric.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.USSBBGeneric.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.USSIndianapolisCA35.class, 7, 600D, 1200D);
        ScoreCounter.register(Ship.USSGreenlingSS213_Srf.class, 7, 200D, 500D);
        ScoreCounter.register(Ship.USSGreenlingSS213_Sub.class, 7, 200D, 500D);
        ScoreCounter.register(Ship.USSGatoSS212_Srf.class, 7, 200D, 500D);
        ScoreCounter.register(Ship.USSGatoSS212_Sub.class, 7, 200D, 500D);
        ScoreCounter.register(Ship.USSWardDD139.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.USSDentDD116.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.USSFletcherDD445.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.USSOBannonDD450.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.USSKiddDD661.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.USSCasablancaCVE55.class, 7, 500D, 1000D);
        ScoreCounter.register(Ship.USSKitkunBayCVE71.class, 7, 500D, 1000D);
        ScoreCounter.register(Ship.USSShamrockBayCVE84.class, 7, 500D, 1000D);
        ScoreCounter.register(Ship.USSEssexCV9.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.USSIntrepidCV11.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.LVT_2WAT.class, 7, 30D, 100D);
        ScoreCounter.register(Ship.DUKW_WAT.class, 7, 30D, 100D);
        ScoreCounter.register(Ship.LCVP.class, 7, 30D, 100D);
        ScoreCounter.register(Ship.HMSIllustriousCV.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.HMSPoWBB.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.HMSKingGeorgeVBB.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.HMSDukeOfYorkBB.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.IJNAkagiCV.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.IJNShokakuCV.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.IJNZuikakuCV.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.IJNCVGeneric.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.IJNBBGeneric.class, 7, 700D, 1400D);
        ScoreCounter.register(Ship.IJNAkizukiDD42.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNAmatsukazeDD41.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNArashiDD41.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNKageroDD41.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNNowakiDD41.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNYukikazeDD41.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNAmatsukazeDD43.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNAmatsukazeDD43WithBeacon.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNNowakiDD43.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNYukikazeDD43.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNAmatsukazeDD45.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNYukikazeDD45.class, 7, 300D, 800D);
        ScoreCounter.register(Ship.IJNFishJunk.class, 7, 200D, 400D);
        ScoreCounter.register(Ship.IJNFishJunkA.class, 7, 250D, 600D);
        ScoreCounter.register(Ship.DaihatsuLC.class, 7, 30D, 100D);
        ScoreCounter.register(BeaconGeneric.class, 9, 35D, 200D);
        ScoreCounter.register(LongBridge.class, 5, 100D, 500D);
    }
}
